
SRC_DIRS := Algorithms Graph DataStructures Tests
SRC := $(foreach dir,$(SRC_DIRS),$(wildcard $(dir)/*.cpp))
OBJ := $(SRC:.cpp=.o)
BIN := main


CXX := g++
CXXFLAGS := -Wall -std=c++11 -g


MAIN := mian.cpp
TESTS := Tests/test_*.cpp

.PHONY: all Main test valgrind clean

all: Main

Main: $(OBJ) $(MAIN)
	$(CXX) $(CXXFLAGS) -o $(BIN) $(MAIN) $(OBJ)

test: $(OBJ) $(TESTS)
	$(CXX) $(CXXFLAGS) -o test_runner $(TESTS) $(OBJ)
	./test_runner

valgrind: Main
	valgrind --leak-check=full ./main

clean:
	rm -f $(OBJ) main test_runner